services:
  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    healthcheck: # optional, recommended since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/healthcheck || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  pocketbase:
    build:
      context: ./pocketbase
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - ./data/pb/data:/pb/pb_data
    healthcheck: # optional, recommended since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
